services:
  easynews-indexer:
    image: ghcr.io/lystad93/easynews_as_indexer_x:latest
    container_name: easynews-indexer
    restart: unless-stopped
    labels:
      - "dockhand.hidden=true"
      - "dockhand.order=1"
    expose:
      - ${PORT}
    env_file:
      - .env
    profiles:
      - easynews-indexer
      - all
